services:
  # Spring Boot 后端服务
  backend:
    image: lianggongcifang/yanami-backend-6670:v1.0
    container_name: yanami-backend-6670
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=yanami-spring
      - SERVER_PORT=8080
    networks:
      - yanami-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Vue 前端服务
  frontend:
    image: lianggongcifang/yanami-frontend-6670:v1.0
    container_name: yanami-frontend-6670
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - yanami-network
    restart: unless-stopped

networks:
  yanami-network:
    driver: bridge
